### ISSUE TITLE
请问有可以跑通的版本吗？

### ISSUE THREAD

**Issue by QHCV** [Rocinate/qmix_playground#1]
谢谢

**Comment by Rocinate** [comment]
> 谢谢

抱歉 这个仓库的东西我有点久没动过了 您要是寻求qmix和其他环境的解决方案的话 可以看看
[marlLib](https://marllib.readthedocs.io/en/latest/)](https://marllib.readthedocs.io/en/latest/)

**Comment by QHCV** [comment]
谢谢！
